'use client';
import { useState } from 'react';
import Link from 'next/link';

const RESUME_TEMPLATE = `JOHN DOE
john.doe@email.com | github.com/johndoe | linkedin.com/in/johndoe
──────────────────────────────────────────────────────────────────
SUMMARY
  Full-stack engineer with 3+ years building scalable web applications.
  Expert in React, Node.js, TypeScript. Passionate about clean code.

SKILLS
  Languages : JavaScript, TypeScript, Python, SQL
  Frontend  : React, Next.js, Tailwind CSS, Framer Motion
  Backend   : Node.js, Express, FastAPI, REST, GraphQL
  Database  : PostgreSQL, MongoDB, Redis, Prisma
  DevOps    : Docker, GitHub Actions, Vercel, AWS

EXPERIENCE
  Software Engineer — TechCorp Inc.              Jan 2023 – Present
  • Built real-time dashboard serving 50k+ daily active users
  • Reduced API latency by 40% via Redis caching layer
  • Led migration from CRA to Next.js 14 App Router

  Frontend Developer — StartupXYZ                Jun 2021 – Dec 2022
  • Developed component library with 60+ reusable components
  • Implemented CI/CD pipeline with 95% test coverage

PROJECTS
  MetaRole AI — AI career co-pilot platform
    Next.js + FastAPI + OpenAI + PostgreSQL + Pinecone

  SecureRxChain — Blockchain drug supply chain
    Solidity + React + Node.js + Web3.js

EDUCATION
  B.Tech Computer Science — Parul University     2020 – 2024
──────────────────────────────────────────────────────────────────
  AI-Generated by MetaRole AI | Tailored for: Senior Full-Stack Engineer
`;

export default function OutputPage() {
  const [activeTab, setActiveTab] = useState<'resume' | 'portfolio' | 'cover'>('resume');
  const [copied, setCopied] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [targetJob, setTargetJob] = useState('Senior Full-Stack Engineer');

  const handleCopy = () => {
    navigator.clipboard.writeText(RESUME_TEMPLATE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRegenerate = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 2000));
    setGenerating(false);
  };

  return (
    <main className="min-h-screen bg-terminal-bg text-terminal-green font-mono">
      <div className="scanlines" aria-hidden="true" />

      <nav className="fixed top-0 w-full z-50 border-b border-terminal-green/20 bg-terminal-bg/95">
        <div className="max-w-7xl mx-auto px-4 h-12 flex items-center justify-between">
          <Link href="/" className="text-terminal-green text-sm tracking-widest">[ METAROLE::AI ]</Link>
          <div className="flex gap-1">
            {(['resume', 'portfolio', 'cover'] as const).map(tab => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-3 py-1 text-xs border transition-all ${
                  activeTab === tab ? 'border-terminal-green bg-terminal-green text-black font-bold' : 'border-terminal-green/30 text-terminal-green/60 hover:border-terminal-green/60'
                }`}
              >
                {tab.toUpperCase()}
              </button>
            ))}
          </div>
        </div>
      </nav>

      <div className="max-w-6xl mx-auto px-4 pt-20 pb-12 grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* LEFT: controls */}
        <div className="space-y-4">
          <div className="border-b border-terminal-green/20 pb-3">
            <p className="text-xs text-terminal-green/40 mb-1">// generate --output</p>
            <h1 className="text-lg font-bold tracking-widest">AI OUTPUT</h1>
          </div>

          <div className="border border-terminal-green/30 p-4 space-y-3">
            <p className="text-xs text-terminal-green/40">// target-role --set</p>
            <input
              value={targetJob}
              onChange={e => setTargetJob(e.target.value)}
              className="w-full bg-transparent border-b border-terminal-green/30 text-terminal-green text-sm outline-none focus:border-terminal-green pb-1"
              placeholder="Target job role..."
            />
          </div>

          <button
            onClick={handleRegenerate}
            disabled={generating}
            className="w-full border-2 border-terminal-green py-2 text-terminal-green text-sm font-bold tracking-widest hover:bg-terminal-green hover:text-black transition-all disabled:opacity-50"
          >
            {generating ? '[ GENERATING... ]' : '[ REGENERATE ]'}
          </button>

          <button
            onClick={handleCopy}
            className="w-full border border-terminal-amber py-2 text-terminal-amber text-sm tracking-widest hover:bg-terminal-amber hover:text-black transition-all"
          >
            {copied ? '[ COPIED! ✓ ]' : '[ COPY TEXT ]'}
          </button>

          <button className="w-full border border-terminal-green/40 py-2 text-terminal-green/60 text-sm tracking-widest hover:border-terminal-green hover:text-terminal-green transition-all">
            [ DOWNLOAD PDF ]
          </button>

          <div className="border border-terminal-green/20 p-3 text-xs">
            <p className="text-terminal-green/40 mb-2">// stats</p>
            <div className="space-y-1">
              <div className="flex justify-between"><span className="text-terminal-green/60">ATS SCORE</span><span className="text-terminal-green">94/100</span></div>
              <div className="flex justify-between"><span className="text-terminal-green/60">KEYWORDS</span><span className="text-terminal-green">28 matched</span></div>
              <div className="flex justify-between"><span className="text-terminal-green/60">LENGTH</span><span className="text-terminal-green">1 page</span></div>
              <div className="flex justify-between"><span className="text-terminal-green/60">FORMAT</span><span className="text-terminal-amber">OPTIMIZED</span></div>
            </div>
          </div>

          <Link href="/dashboard" className="block text-center text-xs text-terminal-green/40 hover:text-terminal-green transition-colors">
            ← back to dashboard
          </Link>
        </div>

        {/* RIGHT: output preview */}
        <div className="lg:col-span-2 border border-terminal-green/40 bg-black/60">
          <div className="flex items-center gap-2 px-4 py-2 border-b border-terminal-green/20">
            <span className="w-2 h-2 rounded-full bg-terminal-green" />
            <span className="text-xs text-terminal-green/40">output ~ {activeTab}</span>
            <span className="ml-auto text-xs text-terminal-amber">{targetJob}</span>
          </div>
          {activeTab === 'resume' && (
            <pre className="p-6 text-xs text-terminal-green/80 whitespace-pre-wrap leading-relaxed overflow-auto max-h-[70vh]">
              {generating ? '> Generating tailored resume...\n\n█████░░░░░░░░░░░░░░░ 40%' : RESUME_TEMPLATE}
            </pre>
          )}
          {activeTab === 'portfolio' && (
            <div className="p-6 space-y-4">
              <p className="text-terminal-green/40 text-xs">// portfolio-site --preview</p>
              <div className="border border-terminal-green/20 p-4">
                <p className="text-terminal-amber text-sm font-bold">johndoe.metarole.ai</p>
                <p className="text-xs text-terminal-green/60 mt-1">Auto-generated portfolio site — React + Tailwind</p>
                <div className="mt-3 grid grid-cols-3 gap-2 text-xs">
                  {['Hero Section', 'Projects Grid', 'Skills Graph', 'Contact Form', 'Blog Ready', 'Dark Mode'].map(item => (
                    <div key={item} className="border border-terminal-green/20 px-2 py-1 text-terminal-green/60">✓ {item}</div>
                  ))}
                </div>
              </div>
              <button className="w-full border-2 border-terminal-amber py-3 text-terminal-amber font-bold tracking-widest hover:bg-terminal-amber hover:text-black transition-all text-sm">
                [ DEPLOY PORTFOLIO ]
              </button>
            </div>
          )}
          {activeTab === 'cover' && (
            <div className="p-6">
              <p className="text-terminal-green/40 text-xs mb-3">// cover-letter --generate --job "{targetJob}"</p>
              <pre className="text-xs text-terminal-green/80 whitespace-pre-wrap leading-relaxed">{`Dear Hiring Manager,

I am writing to express my interest in the ${targetJob}
position. With 3+ years of full-stack engineering experience
and a proven track record of building scalable systems, I am
confident in my ability to contribute significantly to your team.

[AI-generated content continues...]

Generated by MetaRole AI — Tailored for maximum impact.`}</pre>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
