'use client';
import { useState } from 'react';
import Link from 'next/link';

type OutputMode = 'resume' | 'portfolio' | 'cover';

const RESUME_CONTENT = `MANIKANT BINDASS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Full-Stack Developer | Blockchain Engineer | AI/ML
github.com/manikantbindass | linkedin.com/in/manikant-kumar-2255801b6

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SKILLS MATRIX
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Languages    : JavaScript · TypeScript · Python · Solidity · Java
Frontend     : React · Next.js · Tailwind CSS · Framer Motion
Backend      : Node.js · Express · FastAPI · REST APIs
Blockchain   : Ethereum · Hyperledger · Smart Contracts · Web3.js
Database     : PostgreSQL · MongoDB · Redis · Pinecone
DevOps       : Docker · Kubernetes · CI/CD · GitHub Actions
AI/ML        : LangChain · OpenAI API · TensorFlow basics

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXPERIENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[ Full-Stack Developer — Freelance / Projects ]  2023–Present
▸ Built 15+ production-grade web applications across MERN & MEAN stacks
▸ Developed blockchain-based drug supply chain (SecureRxChain) with Solidity
▸ Created AI-powered smart contract auditor (SolGuardAI) using LLMs
▸ Implemented self-healing Kubernetes infrastructure with ML fault detection

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROJECTS (Selected)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
◈ MetaRole AI        — AI career co-pilot (Next.js + FastAPI + OpenAI)
◈ SecureRxChain      — Blockchain drug supply chain (Solidity + Hyperledger)
◈ SolGuardAI         — AI smart contract auditor (Python + LLMs)
◈ AutoHealOps        — Self-healing K8s cluster (Python + RL)
◈ AutoLedgerAI       — Self-healing blockchain network (RL + consensus)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EDUCATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
B.Tech Computer Science — Parul University, Gujarat  (2022–2026)

[AI GENERATED · TAILORED FOR: Senior Full-Stack Engineer @ Vercel]
[MetaRole AI v2.4.1 — match score 94%]`;

const PORTFOLIO_CODE = `<!-- PORTFOLIO GENERATED BY METAROLE AI -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Manikant Bindass — Portfolio</title>
  <style>
    :root { --green: #33ff00; --bg: #0a0a0a; }
    body { background: var(--bg); color: var(--green); font-family: monospace; }
    h1 { font-size: 2rem; border-bottom: 1px solid var(--green); padding-bottom: 1rem; }
    .projects { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
    .card { border: 1px solid rgba(51,255,0,0.3); padding: 1.5rem; }
    .card:hover { border-color: var(--green); background: rgba(51,255,0,0.04); }
  </style>
</head>
<body>
  <h1>MANIKANT BINDASS</h1>
  <p>Full-Stack Dev · Blockchain Engineer · AI/ML</p>
  <div class="projects">
    <div class="card"><h3>MetaRole AI</h3><p>AI career platform...</p></div>
    <div class="card"><h3>SecureRxChain</h3><p>Blockchain supply chain...</p></div>
    <!-- ... more projects auto-generated -->
  </div>
</body>
</html>`;

export default function OutputPage() {
  const [mode, setMode] = useState<OutputMode>('resume');
  const [copied, setCopied] = useState(false);

  const content = mode === 'resume' ? RESUME_CONTENT : mode === 'portfolio' ? PORTFOLIO_CODE : `Dear Hiring Manager,\n\nI am writing to express my strong interest in the Senior Full-Stack Engineer position at Vercel...\n\n[AI TAILORED COVER LETTER — MetaRole AI v2.4.1]`;

  const copy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <main className="bg-terminal-bg text-terminal-green font-mono min-h-screen">
      <div className="scanline-overlay pointer-events-none" />

      <nav className="border-b border-terminal-green/30 px-6 py-3 flex items-center justify-between">
        <Link href="/" className="font-bold tracking-widest">
          <span className="text-terminal-amber">{'>'}</span> METAROLE<span className="text-terminal-amber">.AI</span>
        </Link>
        <Link href="/dashboard" className="text-terminal-green/60 hover:text-terminal-green text-xs">[BACK_TO_DASHBOARD]</Link>
      </nav>

      <div className="max-w-5xl mx-auto px-6 py-12">
        <div className="text-terminal-amber text-xs tracking-widest mb-2">// AI_OUTPUT_ENGINE //</div>
        <h1 className="text-3xl font-bold mb-6">GENERATE OUTPUT</h1>

        {/* Mode Selector */}
        <div className="flex gap-2 mb-6">
          {(['resume', 'portfolio', 'cover'] as OutputMode[]).map(m => (
            <button
              key={m}
              onClick={() => setMode(m)}
              className={`px-4 py-2 text-xs font-bold border transition-all ${
                mode === m
                  ? 'border-terminal-green bg-terminal-green text-terminal-bg'
                  : 'border-terminal-green/30 text-terminal-green/60 hover:border-terminal-green hover:text-terminal-green'
              }`}
            >
              [{m.toUpperCase()}]
            </button>
          ))}
        </div>

        {/* Output Terminal */}
        <div className="border border-terminal-green/40">
          <div className="flex items-center justify-between px-4 py-2 bg-terminal-green/10 border-b border-terminal-green/30">
            <span className="text-xs text-terminal-green/60">
              metarole-ai ~ {mode}-generator v2.4.1
            </span>
            <div className="flex gap-3">
              <button
                onClick={copy}
                className="text-xs border border-terminal-green/30 px-3 py-1 hover:border-terminal-green hover:text-terminal-green text-terminal-green/60 transition-all"
              >
                {copied ? '✓ COPIED' : '[COPY]'}
              </button>
              <button className="text-xs border border-terminal-amber/30 px-3 py-1 hover:border-terminal-amber hover:text-terminal-amber text-terminal-amber/60 transition-all">
                [DOWNLOAD]
              </button>
            </div>
          </div>
          <pre className="p-6 text-xs leading-relaxed text-terminal-green/90 overflow-auto max-h-[600px] whitespace-pre-wrap">
            {content}
          </pre>
        </div>

        <div className="mt-6 text-terminal-green/40 text-xs">
          ● Generated by MetaRole AI — GPT-4 powered · Tailored per job match · {new Date().toISOString()}
        </div>
      </div>
    </main>
  );
}
